#!/bin/bash

set -x

CONFIG=$1
EXTRA_FILE=$2

mkdir -p ./store

if [ "$EXTRA_FILE" != "" ]; then
  cp $EXTRA_FILE ./RomWBW/Source/RomDsk/ROM_512KB/
  FILENAME=$(basename $EXTRA_FILE)
  echo -e "rm ./RomWBW/Source/RomDsk/ROM_512KB/${FILENAME}\n" > /tmp/romwbw-clean-up-script
else
  rm -f /tmp/romwbw-clean-up-script
fi

cp ./apps/hbios/hbios.com ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./apps/driver-fn/driverfn.com ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./RomWBW/Source/Apps/Tune/Tune.com ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./RomWBW/Source/Apps/Tune/Tunes/Backup.pt3 ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./RomWBW/Source/Apps/Tune/Tunes/Demo3.mym ./RomWBW/Source/RomDsk/ROM_512KB/
[ -f ./RomWBW/Source/RomDsk/ROM_512KB/MBASIC.COM ] && mv ./RomWBW/Source/RomDsk/ROM_512KB/MBASIC.COM ./store/
[ -f ./RomWBW/Source/RomDsk/ROM_512KB/FDISK80.COM ] && mv ./RomWBW/Source/RomDsk/ROM_512KB/FDISK80.COM ./store/
[ -f ./RomWBW/Source/RomDsk/ROM_512KB/ZDE.COM ] && mv ./RomWBW/Source/RomDsk/ROM_512KB/ZDE.COM ./store/

cp ./RCZ80_$CONFIG.asm ./RomWBW/Source/HBIOS/Config

patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < systimerinc.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-HBIOS-CBIOS-Added-optional-configuration-MDRAMDISABL.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-AY38910-force-enable.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-tms-user-config.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-force-enable-tms.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-apply-custom-usrrom-image.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-romldr.patch
patch -suN --no-backup-if-mismatch -p1 -d ./RomWBW < 0001-redo-dd-fix-not-accepted-in-upstream.patch
