#!/bin/bash

cp ./apps/hbios/hbios.com ./RomWBW/Source/RomDsk/ROM_512KB/hbios.com
cp ./RCZ80_dino.asm ./RomWBW/Source/HBIOS/Config

function cleanup() {
  rm ./RomWBW/Source/RomDsk/ROM_512KB/hbios.com
  rm ./RomWBW/Source/HBIOS/Config/RCZ80_dino.asm
}

trap cleanup EXIT

(cd ./RomWBW/Source && /mnt/c/Windows/system32/cmd.exe /C "Build${1}.cmd ${@:2}")

