#!/bin/bash

cp ./apps/hbios/hbios.com ./RomWBW/Source/RomDsk/ROM_512KB/hbios.com

function cleanup() {
  rm ./RomWBW/Source/RomDsk/ROM_512KB/hbios.com
}

trap cleanup EXIT

(cd ./RomWBW/Source && /mnt/c/Windows/system32/cmd.exe /C "Build${1}.cmd ${@:2}")

