#!/bin/bash

CONFIG=$1

if [ -f "/tmp/romwbw-clean-up-script" ]; then
  $(cat /tmp/romwbw-clean-up-script)
fi

rm ./RomWBW/Source/RomDsk/ROM_512KB/hbios.com
rm ./RomWBW/Source/RomDsk/ROM_512KB/driverfn.com
rm ./RomWBW/Source/RomDsk/ROM_512KB/Tune.com
rm ./RomWBW/Source/HBIOS/Config/RCZ80_$CONFIG.asm
rm ./RomWBW/Source/RomDsk/ROM_512KB/Backup.pt3
rm ./RomWBW/Source/RomDsk/ROM_512KB/Demo3.mym
cp ./store/MBASIC.COM ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./store/FDISK80.COM ./RomWBW/Source/RomDsk/ROM_512KB/
cp ./store/ZDE.COM ./RomWBW/Source/RomDsk/ROM_512KB/

patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-redo-dd-fix-not-accepted-in-upstream.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-romldr.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-apply-custom-usrrom-image.patch
# patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-dinotron-hack.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-force-enable-tms.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-tms-user-config.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-AY38910-force-enable.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < 0001-HBIOS-CBIOS-Added-optional-configuration-MDRAMDISABL.patch
patch -suN --no-backup-if-mismatch -R -p1 -d ./RomWBW < systimerinc.patch

 rm -f ./RomWBW/Binary/CPM3/bdos3.spr
 rm -f ./RomWBW/Binary/CPM3/bios3.spr
 rm -f ./RomWBW/Binary/CPM3/bnkbdos3.spr
 rm -f ./RomWBW/Binary/CPM3/bnkbios3.spr
 rm -f ./RomWBW/Binary/CPM3/cpm3fix.pat
 rm -f ./RomWBW/Binary/CPM3/genbnk.dat
 rm -f ./RomWBW/Binary/CPM3/gencpm.dat
 rm -f ./RomWBW/Binary/CPM3/genres.dat
 rm -f ./RomWBW/Binary/CPM3/readme.1st
 rm -f ./RomWBW/Binary/CPM3/resbdos3.spr
 rm -f ./RomWBW/Binary/ZPM3/bnkbdos3.spr
 rm -f ./RomWBW/Binary/ZPM3/bnkbios3.spr
 rm -f ./RomWBW/Binary/ZPM3/gencpm.dat
 rm -f ./RomWBW/Binary/ZPM3/resbdos3.spr
 rm -f ./RomWBW/Binary/ZPM3/zinstal.zpm
 rm -f ./RomWBW/Source/ZPM3/cpmldr.com
