#!/bin/bash

CONFIG=$3

./romwbw-build-prep $CONFIG

function cleanup() {
  ./romwbw-build-cleanup $CONFIG
}

trap cleanup EXIT

(cd ./RomWBW/Source && /mnt/c/Windows/system32/cmd.exe /C "Build${1}.cmd ${@:2}")

