#!/bin/bash

FAILED=0

make apps -s

for i in ./romwbw-tests/*.test; do
  filename=$(basename $i)
  filename="${filename%.*}"
  if ! ./test-rc-hbios "$filename" "no-tail"; then
    FAILED=1
  fi
done

exit $FAILED
