
	PUBLIC	_hbVdaInit
	PUBLIC	_hbVdaWriteChar
	PUBLIC	_hbVdaSetCursorPosition
	SECTION CODE

BF_VDA		EQU	$40
BF_VDAINI	EQU	BF_VDA + 0	; INITIALIZE VDU
BF_VDAQRY	EQU	BF_VDA + 1	; QUERY VDU STATUS
BF_VDARES	EQU	BF_VDA + 2	; SOFT RESET VDU
BF_VDADEV	EQU	BF_VDA + 3	; DEVICE INFO
BF_VDASCS	EQU	BF_VDA + 4	; SET CURSOR STYLE
BF_VDASCP	EQU	BF_VDA + 5	; SET CURSOR POSITION
BF_VDASAT	EQU	BF_VDA + 6	; SET CHARACTER ATTRIBUTE
BF_VDASCO	EQU	BF_VDA + 7	; SET CHARACTER COLOR
BF_VDAWRC	EQU	BF_VDA + 8	; WRITE CHARACTER
BF_VDAFIL	EQU	BF_VDA + 9	; FILL
BF_VDACPY	EQU	BF_VDA + 10	; COPY
BF_VDASCR	EQU	BF_VDA + 11	; SCROLL
BF_VDAKST	EQU	BF_VDA + 12	; GET KEYBOARD STATUS
BF_VDAKFL	EQU	BF_VDA + 13	; FLUSH KEYBOARD BUFFER
BF_VDAKRD	EQU	BF_VDA + 14	; READ KEYBOARD


; extern byte hbVdaInit(byte driver, byte mode, void* fontBitMap = 0);

_hbVdaInit:
	LD	HL, 2
	ADD	HL, SP
	LD	B, BF_VDAINI
  	LD 	C, (HL)		; DRIVER INDEX
	INC	HL
	LD	E, (HL)		; MODE
	INC	HL
	LD	A, (HL)		; BIT MAP DATA
	INC	HL
	LD	H, (HL)
	LD	A, L
	RST	08
	LD	L, A
	RET

; extern byte hbVdaWriteChar(byte driver, char ch);
_hbVdaWriteChar:
	LD	HL, 2
	ADD	HL, SP
	LD	B, BF_VDAWRC
  	LD 	C, (HL)
	INC	HL
	LD	E, (HL)
	RST	08
	LD	L, A
	RET

; extern byte hbVdaSetCursorPosition(byte driver, byte row, byte col);
_hbVdaSetCursorPosition:
	LD	HL, 2
	ADD	HL, SP
	LD	B, BF_VDASCP
  	LD 	C, (HL)
	INC	HL
	LD	D, (HL)
	INC	HL
	LD	E, (HL)
	RST	08
	LD	L, A
	RET

	SECTION IGNORE
