#!/bin/bash

if [ "$CI" == "true" ]; then
  TIMERCOUNT=80
  TIMEPAUSE=1
else
  TIMERCOUNT=20
  TIMEPAUSE=0.1
fi

if [[ "$1" = "gt" ]]; then
  TEST_OPER="-gt"
  TEST_VALUE="$2"
  TEST_PATTERN="$3"
else
  TEST_OPER="-eq"
  TEST_VALUE="$1"
  TEST_PATTERN="$2"
fi

NEXT_WAIT_TIME=0
until [ $(grep -i -c "$TEST_PATTERN" /tmp/rcoutput.txt) $TEST_OPER "$TEST_VALUE" ] || [ $NEXT_WAIT_TIME -eq $TIMERCOUNT ]; do
  (( NEXT_WAIT_TIME++ ))
  sleep $TIMEPAUSE
done

X=$(grep -i -c "$TEST_PATTERN" /tmp/rcoutput.txt)
FN="if [[ ! \"$X\" ${TEST_OPER} \"$TEST_VALUE\" ]]; then exit 1; fi"
eval $FN
