#!/bin/bash

sudo dos2unix  /tmp/rcoutput.txt > /dev/null 2>&1

if [ "$CI" == "true" ]; then
  TIMERCOUNT=80
  TIMEPAUSE=1
else
  TIMERCOUNT=20
  TIMEPAUSE=0.1
fi

TEST_OPER="-eq"
TEST_VALUE=$1
TEST_PATTERN="$(sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g' $2)"

NEXT_WAIT_TIME=0
until [ $(grep  -Pzo -i -c "$TEST_PATTERN" /tmp/rcoutput.txt) $TEST_OPER "$TEST_VALUE" ] || [ $NEXT_WAIT_TIME -eq $TIMERCOUNT ]; do
  (( NEXT_WAIT_TIME++ ))
  sleep $TIMEPAUSE
done

X=$(grep -Pzo  -i -c "$TEST_PATTERN" /tmp/rcoutput.txt)
FN="if [[ ! \"$X\" ${TEST_OPER} \"$TEST_VALUE\" ]]; then exit 1; fi"
eval $FN
