.PHONY: all
.PHONY: hbios
.PHONY: inttest
.PHONY: driver-fn
.PHONY: extromldr

all: hbios inttest driver-fn extromldr

extromldr:
	$(MAKE) --directory extromldr

driver-fn:
	$(MAKE) --directory driver-fn

hbios:
	$(MAKE) --directory hbios

inttest:
	$(MAKE) --directory inttest
