.PHONY: all
.PHONY: hbios
.PHONY: inttest
.PHONY: driver-fn

all: hbios inttest driver-fn

driver-fn:
	$(MAKE) --directory driver-fn

hbios:
	$(MAKE) --directory hbios

inttest:
	$(MAKE) --directory inttest
